version: "3"
services:
  app:
    image: flask-app
    volumes:
      - .:/app
    links:
      - db
    ports:
      - "5000:5000"
    command: python ./app/app.py

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
