version: "3"
services:
  app:
    image: gcr.io/junyiacademytest1/k8s-101-flask:justin.v2
    volumes:
      - .:/app
    links:
      - db
    ports:
      - "5000:5000"
    command: python ./app/app.py

  db:
    # image: mysql:5.7
    image: gcr.io/junyiacademytest1/k8s-101-mysql:justin.v1
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
