apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-101-mysql
  labels:
    app: k8s-101-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-101-mysql
    spec:
      containers:
      - name: mysql
        image: gcr.io/junyiacademytest1/k8s-101-mysql:justin.v1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        imagePullPolicy: Always
        ports:
        - containerPort: 3306